name: Check TimeZone Version

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: Build with dotnet
        run: dotnet build src/System.Runtime.TimeZoneData /t:CheckVersion 
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./src/System.Runtime.TimeZoneData/data/version
      - name: Check outputs
        run: echo ${{ steps.version.outputs.content }}
      - name: Edit XML
        uses: Mudlet/xmlstarlet-action@v1.1
        with: 
          args: ed -O -P --inplace -u "/Project/PropertyGroup/TimeZoneDataVersion" -v ${{ steps.version.outputs.content }} src/System.Runtime.TimeZoneData/System.Runtime.TimeZoneData.csproj   
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3    
        with: 
          title: Update IANA Timezone version
          branch: auto-update-tz-ver
          delete-branch: true   
